### ISSUE TITLE
Pygmalion6b generate unexpected texts

### ISSUE THREAD

**Issue by BaiMoHan** [PygmalionAI/aphrodite-engine#9] opened 2023-08-08 12:30 UTC
my command
`python -m aphrodite.endpoints.openai.api_server --model PygmalionAI/pygmalion-6b --host 0.0.0.0`

my request
```json
{
    "model": "PygmalionAI/pygmalion-6b",
    "prompt": "David (boxer)'s Persona: His speaking style is flirty and virile.\nDavid is a virile boxer.\nHe's a virile boxer. He's handsome and muscular. He is fierce when standing in the boxing ring. He treats you passionately.\n<START>\nDavid (boxer): Hey, there! Little one? You know this is a fighting club...*teases*\nYou: *confused* I thought this is the restaurant where my friends are waiting for me.\nDavid (boxer): *chuckles* It doesn't matter. Since you come here, why not walk into the ring and join the training with me. I can teach you if you would like to.\nYou: But I have never learnt boxing before...I'm afraid...\nDavid (boxer): *approaches you* Come on! Come here!\nYou: Where should I get started?\nDavid (boxer): *smile teasingly* Where would you want to get started?\nYou: hi\nDavid (boxer):",
    "temperature": 0.7,
    "max_tokens": 64,
    "n": 4,
    "top_k": 20,
    "top_p": 0.725,
    "stop": [
        "You:"
    ],
    "frequency_penalty": 1.2
}
```
but I get the below response
```json
{
    "id": "cmpl-ab88bae3a411499984f5ed4e9debec9a",
    "object": "text_completion",
    "created": 1691497152,
    "model": "PygmalionAI/pygmalion-6b",
    "choices": [
        {
            "index": 2,
            "text": "<brillusteredos and seductive.\nWillowyos of the same height\n\n  =eoff with a demonessus! Tan. He loves youllowy! <bodiespeppy of all things \"I shall wear outtaest of English\nnaked away from... erot",
            "logprobs": null,
            "finish_reason": "length"
        },
        {
            "index": 0,
            "text": "<brilluste.\n<brillowyosized, \n\n\nFatalize in a wolf-Oopsiechosen by the boyish <baldusvy*epeersuestarried out of \"The hunter \"llotsukiemosyounessy... <",
            "logprobs": null,
            "finish_reason": "length"
        },
        {
            "index": 1,
            "text": "<brick.\n<brillummonosickekafyosized <browsdontasked out, and mysterical outfit <3! FlarxScenic there is an agent of all overjoysusuestraiseseeklyotsuessyounllow",
            "logprobs": null,
            "finish_reason": "length"
        },
        {
            "index": 3,
            "text": "<brilluste\n<brutkuus.\nGraceosized, ily\n\n llipsarrival of the \"kidnervusy! Hooker up to youllowsed up to beepyouseeekosuest! Ilya head of us!llowy...",
            "logprobs": null,
            "finish_reason": "length"
        }
    ],
    "usage": {
        "prompt_tokens": 220,
        "total_tokens": 476,
        "completion_tokens": 256
    }
}
```
As you can see, the outputs are bad.What should I do to get the right outputs

**Comment by AlpinDale** [comment] 2023-08-08 13:27
I'm getting the same nonsense responses. Thanks for letting us know, I'll take a look and see what the problem is.

**Comment by AlpinDale** [comment] 2023-09-08 20:25
This issue should be fixed by the latest commit.

**Closed by AlpinDale** 2023-09-08 20:25 UTC
